{% set version = '0.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nidapfunctions
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/NIDAP-Community/nidapFunctions
  git_tag: v0.5.0

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests:
requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base ==4.1.3

  run:
    - r-base ==4.1.3

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('nidapFunctions')"           # [not win]
    - "\"%R%\" -e \"library('nidapFunctions')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/NIDAP-Community/nidapFunctions
  license: MIT
  summary: Useful Tools for Developing in NIDAP Code Workbook.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'

# The original CRAN metadata for this package was:

# Package: nidapFunctions
# Type: Package
# Title: Tools for NIDAP Code Workbook Templates
# Version: 0.1
# Date: 2023-04-20
# Authors@R: person("Cam", "Maggie", email = "maggie.cam@nih.gov", role = c("cre","aut"))
# Maintainer: Cam Maggie <maggie.cam@nih.gov>
# URL: https://github.com/NIDAP-Community/nidapFunctions
# BugReports: https://github.com/NIDAP-Community/nidapFunctions/issues
# Description: Useful Tools for Developing in NIDAP Code Workbook.
# Depends: R (>= 4.1.3)
# Imports: base
# Suggests:
# License: MIT
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.3
# VignetteBuilder: knitr
# Language: en-US

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
